version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: login14ms  
      MYSQL_DATABASE: nodejs_signup
      MYSQL_USER: salman
      MYSQL_PASSWORD: salman14ms
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql  # MySQL data volume
    networks:
      - app_network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8083:8080"
    networks:
      - app_network

  myapp:
    image: nodejsapp:1.2
    ports:
      - "3000:3000"
    volumes:
      - ./myapp_data:/usr/src/app  # Myapp code volume
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
